/*jshint esversion: 6 */

const data = {
  categories: [
    {
      name: 'Biology',
      icon:
        'https://images.unsplash.com/photo-1507413245164-6160d8298b31?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80',
    },
    {
      name: 'English',
      icon:
        'https://png.pngtree.com/png-clipart/20190905/original/pngtree-english-class-study-class-png-image_4515224.jpg',
    },
  ],
  Biology: [
    {
      id: 1,
      question:
        'Which of the following is a large blood vessel that carries blood away from the heart?',
      a: 'Vein',
      b: 'Artery',
      c: 'Capillary',
      d: 'Nerve',
      correct: 'b',
    },
    {
      id: 2,
      question:
        'Which of the following is not a member of the vitamin B complex?',
      a: 'Thiamine',
      b: 'Riboflavin',
      c: 'Folic acid',
      d: 'Ascorbic acid',
      correct: 'd',
    },
    {
      id: 3,
      question: 'Fungi are plants that lack:',
      a: 'Oxygen',
      b: 'Carbon dioxide',
      c: 'Chlorophyll',
      d: 'None of these',
      correct: 'c',
    },
    {
      id: 4,
      question: 'What makes a reptile a reptile?',
      a: 'Cold blooded',
      b: 'Warm Blooded',
      c: 'Non-Hearing',
      d: 'Egg-laying',
      correct: 'd',
    },
    {
      id: 5,
      question: 'Which blood vessels have the smallest diameter?',
      a: 'Capillaries',
      b: 'Arterioles',
      c: 'Venules',
      d: 'Lymphatic',
      correct: 'a',
    },
    {
      id: 6,
      question: 'Which of the following is an air-borne disease?',
      a: 'Measles',
      b: 'Typhoid',
      c: 'Pink eye',
      d: 'sNone of the above',
      correct: 'a',
    },
    {
      id: 7,
      question:
        'A yellow dust appears on the fingers, whenever we touch the middle of a flower. These tiny yellow grains are one of the most precious substances in nature because they contain the secret of plant life.  What is this dust called?',
      a: 'Pollen',
      b: 'Sperm',
      c: 'Spore',
      d: 'Sporocyst',
      correct: 'a',
    },
    {
      id: 8,
      question: 'Which organ of the body produces the fluid known as bile?',
      a: 'Liver',
      b: 'Pancreas',
      c: 'Gall bladder',
      d: 'Kidney',
      correct: 'a',
    },
    {
      id: 9,
      question: 'Which of the following hormones is a steroid?',
      a: 'Estrogen',
      b: 'Glucagon',
      c: 'Insulin',
      d: 'Oxytocin',
      correct: 'a',
    },
    {
      id: 10,
      question: 'Which one of the following is not a function of the liver?',
      a: 'Regulation of blood sugar',
      b: 'Enzyme activation',
      c: 'Detoxification',
      d: 'Reproduction',
      correct: 'd',
    },
  ],
  English: [
    {
      id: 1,
      question:
        'If there is no gain in being proud, then lets all learn to be ________',
      a: 'gentle',
      b: 'honest',
      c: 'humble',
      d: 'polite',
      correct: 'd',
    },
    {
      id: 2,
      question: 'The boy quietly entered the classroom',
      a: 'gently',
      b: 'immediately',
      c: 'nosily',
      d: 'suddenly',
      correct: 'b',
    },
    {
      id: 3,
      question:
        'While two of the visitors looked familiar the other five looked rather',
      a: 'serious',
      b: 'rough',
      c: 'strange',
      d: 'hostile',
      correct: 'c',
    },
    {
      id: 4,
      question:
        'We all pray the man’s rise will be as sudden as his _ has been',
      a: 'lines',
      b: 'disappointment',
      c: 'fall',
      d: 'down',
      correct: 'c',
    },
    {
      id: 5,
      question:
        'The spectators are all expected to depart after the closing ceremony',
      a: 'arrive',
      b: 'disappear',
      c: 'leave',
      d: 'remain',
      correct: 'a',
    },
    {
      id: 6,
      question: 'You will be punished for doing that',
      a: 'beaten',
      b: 'praised',
      c: 'slapped',
      d: 'pais',
      correct: 'b',
    },
    {
      id: 7,
      question: 'The match _ before it started raining',
      a: 'had ended',
      b: 'had end',
      c: 'has ended',
      d: 'have end',
      correct: 'b',
    },
    {
      id: 8,
      question: 'The pencil ___ was stolen belongs to he',
      a: 'which',
      b: 'who',
      c: 'whom',
      d: 'whose',
      correct: 'a',
    },
    {
      id: 9,
      question: 'He _____ his car in the garage last night',
      a: 'leaves',
      b: 'leaves',
      c: 'left',
      d: 'leaved',
      correct: 'c',
    },
    {
      id: 10,
      question: 'Did john buy that goat?',
      a: 'yes',
      b: 'he, did not',
      c: 'no, he did ',
      d: 'no, he won’t',
      correct: 'd',
    },
  ],
};

export default data;
